export interface McRealm { name: string; addr: string; verified: boolean; online: boolean; players: number; votes: number; tags: string[]; }
export const MC_REALMS: McRealm[] = [
  { name: "null\u0027s World", addr: "wss://nullsworld.net", verified: true, online: true, players: 0, votes: 58, tags: ["PVP", "MINIGAMES", "PVE", "SURVIVAL", "CREATIVE", "SKYBLOCK", "RPG", "MISCELLANEOUS"] },
  { name: "ZythMC", addr: "wss://mc.zyth.me", verified: true, online: true, players: 0, votes: 55, tags: ["MISCELLANEOUS", "PVP", "SURVIVAL", "FACTIONS"] },
  { name: "AsianF4rmer", addr: "wss://asianf4rmer.org", verified: true, online: false, players: 0, votes: 53, tags: ["PVP", "PVE", "SURVIVAL", "SKYBLOCK", "RPG", "MISCELLANEOUS"] },
  { name: "GalacticPVP", addr: "wss://galacticpvp.eagler.host", verified: true, online: true, players: 0, votes: 43, tags: ["PVP", "MINIGAMES", "FACTIONS", "SURVIVAL", "MISCELLANEOUS"] },
  { name: "Aeon Network", addr: "wss://aeon-network.net/", verified: true, online: true, players: 0, votes: 39, tags: ["PVP", "PVE", "MINIGAMES", "SURVIVAL", "CREATIVE", "MISCELLANEOUS"] },
  { name: "SME MC", addr: "wss://play.sme-mc.us/", verified: true, online: true, players: 8, votes: 32, tags: ["SURVIVAL", "PVP", "MISCELLANEOUS", "CREATIVE", "MINIGAMES"] },
  { name: "xenaMC by frogie\u0027s arcade", addr: "wss://xenamc.com", verified: true, online: true, players: 0, votes: 29, tags: ["PVP", "MINIGAMES", "SURVIVAL", "SKYBLOCK", "MISCELLANEOUS"] },
  { name: "Lunox", addr: "wss://lunox.lol", verified: true, online: true, players: 0, votes: 24, tags: ["PVP", "SURVIVAL", "MINIGAMES"] },
  { name: "Bagel SMP", addr: "wss://esl.bagelsmp.com", verified: true, online: true, players: 0, votes: 23, tags: ["PVP", "PVE", "SURVIVAL"] },
  { name: "SkeletonMC", addr: "wss://eagler.skeletonmc.com", verified: true, online: true, players: 0, votes: 15, tags: ["SURVIVAL", "PVP", "PVE"] },
  { name: "JazhdoMC", addr: "wss://itsjaz.com", verified: true, online: true, players: 0, votes: 14, tags: ["SURVIVAL", "CREATIVE", "PVP", "SKYBLOCK", "MINIGAMES"] },
  { name: "mexicraft", addr: "wss://prysm.lol", verified: true, online: true, players: 11, votes: 13, tags: ["MINIGAMES", "SURVIVAL", "CREATIVE", "PVP", "SKYBLOCK"] },
  { name: "ShadowFlare like Donut", addr: "wss://shadowflare.hidenplay.net", verified: true, online: true, players: 0, votes: 9, tags: ["PVP", "PVE", "SURVIVAL", "CREATIVE", "PRISON", "MISCELLANEOUS"] },
  { name: "Nomad Anarchy", addr: "wss://play.nomadanarchy.online", verified: true, online: true, players: 0, votes: 6, tags: ["MISCELLANEOUS", "SURVIVAL", "PVP"] },
  { name: "SkyFrameSMP", addr: "wss://play.skyframesmp.dev", verified: true, online: true, players: 0, votes: 5, tags: ["PVP", "SURVIVAL", "MISCELLANEOUS"] },
  { name: "ArchyVerseV", addr: "wss://mc.archyverse.org", verified: true, online: true, players: 0, votes: 4, tags: ["PVP", "SURVIVAL", "SKYBLOCK", "MISCELLANEOUS", "RPG", "PVE", "FACTIONS", "MINIGAMES", "CREATIVE"] },
  { name: "ChillSurvival", addr: "wss://chillsurvival.eagler.host", verified: true, online: true, players: 0, votes: 4, tags: ["SURVIVAL", "MISCELLANEOUS"] },
  { name: "Hyper Network", addr: "wss://eag.hyper-network.xyz", verified: true, online: true, players: 0, votes: 4, tags: ["PVP", "MINIGAMES", "FACTIONS", "SURVIVAL", "SKYBLOCK"] },
  { name: "RigelMC - Free OP", addr: "wss://eagler.rigelmc.org", verified: true, online: true, players: 0, votes: 4, tags: ["MISCELLANEOUS", "CREATIVE", "SURVIVAL", "PVP"] },
  { name: "WebMC", addr: "wss://play.webmc.fun", verified: true, online: true, players: 27, votes: 3, tags: ["SKYBLOCK", "SURVIVAL", "PVE", "PVP", "MISCELLANEOUS", "CREATIVE"] },
  { name: "1B2T", addr: "wss://mc.1b2t.xyz", verified: true, online: true, players: 0, votes: 2, tags: ["PVP", "PVE", "SURVIVAL", "MISCELLANEOUS"] },
  { name: "3b3t", addr: "wss://debug-winxpserver.loophole.site", verified: true, online: true, players: 0, votes: 2, tags: ["SURVIVAL"] },
  { name: "Broken", addr: "wss://broken.eagler.host", verified: true, online: true, players: 0, votes: 2, tags: ["PVP", "SURVIVAL"] },
  { name: "Pray SMP", addr: "wss://play-pray-smp.prayoadmii.qzz.io/", verified: true, online: true, players: 0, votes: 2, tags: ["SURVIVAL"] },
  { name: "BedWetr [Natural disasters :\u003e, Pillars Of Fortune]", addr: "wss://bedw3tr.bytommy.uk", verified: true, online: true, players: 18, votes: 1, tags: ["SURVIVAL", "MINIGAMES", "PVP", "MISCELLANEOUS"] },
  { name: "ChaseSMP", addr: "wss://chasesmp.eagler.host", verified: true, online: true, players: 0, votes: 1, tags: ["PVP", "MISCELLANEOUS"] },
  { name: "CrackedPvP", addr: "wss://play.crackedpvp.club", verified: true, online: true, players: 69, votes: 1, tags: ["PVP", "SURVIVAL", "MISCELLANEOUS"] },
  { name: "CraftPublic", addr: "wss://eagler.qilk.de", verified: true, online: true, players: 0, votes: 1, tags: ["SURVIVAL", "PVP", "PVE", "MISCELLANEOUS"] },
  { name: "FreedomOP", addr: "wss://freedomop.net", verified: true, online: true, players: 0, votes: 1, tags: ["CREATIVE", "SURVIVAL", "PVP"] },
  { name: "GG SMP", addr: "wss://ggsmp.net", verified: true, online: true, players: 26, votes: 1, tags: ["PVP", "PVE", "SURVIVAL", "PRISON", "FACTIONS"] },
  { name: "KrypticMC", addr: "wss://krypticmc.net", verified: true, online: true, players: 0, votes: 1, tags: ["MINIGAMES", "PVP", "SURVIVAL", "PRISON", "PVE", "MISCELLANEOUS"] },
  { name: "MaceSMP", addr: "wss://strengthnetwork.org", verified: true, online: true, players: 0, votes: 1, tags: ["SURVIVAL", "PVP", "MISCELLANEOUS"] },
  { name: "mexicraft survival 1.8-1.12", addr: "wss://server.mexi.lol", verified: true, online: true, players: 11, votes: 1, tags: ["SURVIVAL"] },
  { name: "MoonlightMC", addr: "wss://eagler.moonlightmc.uk", verified: true, online: true, players: 0, votes: 1, tags: ["SURVIVAL", "MISCELLANEOUS", "PVP"] },
  { name: "Potatos and Fries", addr: "wss://potatos-andfries.eagler.host", verified: true, online: true, players: 0, votes: 1, tags: ["PVP", "SURVIVAL", "PVE", "MISCELLANEOUS"] },
  { name: "Rezam Network", addr: "wss://ec.rezam.xyz", verified: true, online: true, players: 0, votes: 1, tags: ["PVP", "MINIGAMES", "SURVIVAL"] },
  { name: "SummitK2 MC server", addr: "wss://summitk2.playit.plus", verified: true, online: true, players: 0, votes: 1, tags: ["SURVIVAL"] },
  { name: "WanderwoodSMP", addr: "wss://wanderwoodsmp.com", verified: true, online: true, players: 0, votes: 1, tags: ["PVP", "MINIGAMES", "SURVIVAL"] },
  { name: "ZeroSanity", addr: "wss://eagler.zerosanity.net", verified: true, online: true, players: 0, votes: 1, tags: ["PVP", "PVE", "MISCELLANEOUS", "RPG", "SURVIVAL"] },
  { name: "2builders2eaglers (nostalgic 2017 2b2t map - very large world download of spawn!)", addr: "wss://2b2e.me", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "2panes1te | 1.12.2 anarchy", addr: "wss://eagler.2p1t.com", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "MISCELLANEOUS"] },
  { name: "3am", addr: "wss://3am.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "SURVIVAL"] },
  { name: "3e3c Lifesteal", addr: "wss://3e3c.org", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "PVE", "SURVIVAL"] },
  { name: "AcentraMC", addr: "wss://play.acentramc.com", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "PVE", "MINIGAMES"] },
  { name: "AdderallMC", addr: "wss://adderall.ir", verified: true, online: true, players: 215, votes: 0, tags: ["SURVIVAL", "SKYBLOCK", "CREATIVE", "MISCELLANEOUS", "PVP", "PVE"] },
  { name: "ADSCRAFT / The Porcupine Network", addr: "wss://mc.canarycraft.org", verified: true, online: false, players: 0, votes: 0, tags: ["FACTIONS", "SURVIVAL", "MISCELLANEOUS", "PVP", "RPG"] },
  { name: "Adventure Islands", addr: "wss://adventureislands.eu:25567/", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "FACTIONS"] },
  { name: "Aether Network", addr: "wss://aether-network.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "SURVIVAL"] },
  { name: "AnarchMC", addr: "wss://web.aesthetiful.com", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "✨ ZX NETWORK ✨", addr: "wss://z-x.cc.cd/", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "SURVIVAL"] },
  { name: "Asspixel Network", addr: "wss://mc.asspixel.net", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "PVE", "MINIGAMES", "SKYBLOCK"] },
  { name: "AutoHvH", addr: "wss://eagler.autohvh.club", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "SURVIVAL"] },
  { name: "Based MC", addr: "wss://eagler.basedmc.club", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "PVP", "PVE"] },
  { name: "Bendies Cool Server", addr: "wss://bendie.tuff.tf", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "RPG", "MISCELLANEOUS", "FACTIONS", "PVP"] },
  { name: "BoxSmp", addr: "wss://box-smp.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "SKYBLOCK", "PRISON", "MINIGAMES", "PVP"] },
  { name: "CastersMC", addr: "wss://mc.castersmc.org", verified: true, online: false, players: 0, votes: 0, tags: ["FACTIONS", "MINIGAMES", "SURVIVAL", "MISCELLANEOUS", "PVE", "PVP"] },
  { name: "CathCraft - 1.6.4", addr: "wss://cathcraft.cirsi.us", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "MISCELLANEOUS", "PVP", "PVE"] },
  { name: "CheeseBurger Network", addr: "wss://play.cburger.net", verified: true, online: true, players: 7, votes: 0, tags: ["PVP", "SURVIVAL", "MISCELLANEOUS", "SKYBLOCK"] },
  { name: "Citri | 1.21 WORLD GEN", addr: "wss://play.citri.xyz", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "MISCELLANEOUS", "PVP", "MINIGAMES", "PVE"] },
  { name: "Clever Teaching", addr: "wss://clever-teaching.com", verified: true, online: true, players: 107, votes: 0, tags: ["SURVIVAL", "CREATIVE", "SKYBLOCK", "PRISON", "PVE", "PVP", "MINIGAMES", "MISCELLANEOUS"] },
  { name: "CliveEagleflow ", addr: "wss://cliveoverflow.com:30065", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "PVE", "SURVIVAL", "MISCELLANEOUS"] },
  { name: "ColdHeart Survival", addr: "wss://eagler.coldheart.net", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "PVE"] },
  { name: "Combat CLub", addr: "wss://combat-clubs.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "MINIGAMES", "RPG", "MISCELLANEOUS"] },
  { name: "Communist MC", addr: "wss://cmc.tf", verified: true, online: true, players: 13, votes: 0, tags: ["SURVIVAL"] },
  { name: "Contrabell | LIFESTEAL SEASON 1", addr: "wss://contrabell.bytommy.uk", verified: true, online: true, players: 0, votes: 0, tags: ["MINIGAMES", "MISCELLANEOUS", "PVP"] },
  { name: "CoreClub", addr: "wss://play.coreclub.cc", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "SURVIVAL"] },
  { name: "Create Haven", addr: "wss://eagler.kyle-hosting.xyz ", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "MINIGAMES", "SKYBLOCK", "PRISON", "PVP", "PVE", "CREATIVE", "MISCELLANEOUS"] },
  { name: "creayun / ayunboom", addr: "wss://sus.shhnowisnottheti.me", verified: true, online: false, players: 0, votes: 0, tags: ["CREATIVE", "MISCELLANEOUS", "SURVIVAL"] },
  { name: "Dakto INC", addr: "wss://eaglercraft.daktoinc.co.uk", verified: true, online: true, players: 2, votes: 0, tags: ["PVP", "PVE", "SURVIVAL", "CREATIVE"] },
  { name: "DaServerV3", addr: "wss://play.hostinghaven.us:45947", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "MISCELLANEOUS", "PVP"] },
  { name: "DazedSMP", addr: "wss://dazed.galacticnet.cfd", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "FACTIONS", "RPG"] },
  { name: "Demons-smp ", addr: "wss://demons-smp.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "MINIGAMES", "SURVIVAL"] },
  { name: "Divine Network", addr: "wss://play.divinenet.space", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "PVP", "MINIGAMES", "MISCELLANEOUS"] },
  { name: "DragonFireMC", addr: "wss://eagler.dragonfire.world", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "MISCELLANEOUS"] },
  { name: "DylanMC Lifesteal S1 + TNT Run + Bedwars", addr: "wss://play.monacoeducation.info", verified: true, online: true, players: 34, votes: 0, tags: ["PVP", "MINIGAMES", "SURVIVAL", "MISCELLANEOUS"] },
  { name: "Eagler proxy 4 mineland", addr: "wss://webmc.xyz/api/cors?url=ws://eagler.servegame.com:7002", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "SKYBLOCK", "MINIGAMES", "CREATIVE", "PRISON", "MISCELLANEOUS"] },
  { name: "EaglerLifeSMP", addr: "wss://eaglerlifesmp.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "PVP", "MISCELLANEOUS"] },
  { name: "EaglerPixel", addr: "wss://eaglerpixel.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "MINIGAMES", "SURVIVAL", "SKYBLOCK", "CREATIVE"] },
  { name: "EagleSMP", addr: "wss://eagler.eaglesmp.org", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "MISCELLANEOUS", "PVP", "PVE"] },
  { name: "Ethereal", addr: "wss://ethereal.mov", verified: true, online: true, players: 30, votes: 0, tags: ["PVP", "PVE", "SURVIVAL", "MINIGAMES", "MISCELLANEOUS"] },
  { name: "Expandion 1.5.2 RU", addr: "wss://ec.expandion.su", verified: true, online: true, players: 8, votes: 0, tags: ["SURVIVAL", "MISCELLANEOUS", "SKYBLOCK", "PVE", "FACTIONS"] },
  { name: "Feaber MC", addr: "wss://eagler.feaber.jp", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "CREATIVE", "PVE"] },
  { name: "FedralSMP", addr: "wss://3le.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "PVP"] },
  { name: "FrienMC", addr: "wss://eagler.frien.org", verified: true, online: false, players: 0, votes: 0, tags: ["PVE", "SURVIVAL", "MISCELLANEOUS"] },
  { name: "FuchsMC Network", addr: "wss://eagler.fuchsmc.net", verified: true, online: true, players: 0, votes: 0, tags: ["MISCELLANEOUS", "SURVIVAL", "MINIGAMES", "PVP", "PVE", "SKYBLOCK"] },
  { name: "Galaxy Network", addr: "wss://play.hostinghaven.us:45720", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "GalaxyMC Server", addr: "wss://galaxymc.eagler.host", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "CREATIVE"] },
  { name: "GekkoGames Network", addr: "wss://eagler.gekkogames.xyz:25698", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "PVE", "MISCELLANEOUS"] },
  { name: "GreenzBeanz SMP", addr: "wss://greenzbeanz-smp.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "HighSkies SMP", addr: "wss://highskies-smp.eagler.host", verified: true, online: false, players: 0, votes: 0, tags: ["PVE", "PVP", "SURVIVAL"] },
  { name: "HollowNet", addr: "wss://hollow.network", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "PVE", "MISCELLANEOUS"] },
  { name: "Huntools", addr: "wss://craft.huntools-bot.xyz", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "MINIGAMES", "MISCELLANEOUS"] },
  { name: "IMC.RE", addr: "wss://ws.imc.re/server", verified: true, online: true, players: 9, votes: 0, tags: ["PVP", "PVE", "MINIGAMES", "SURVIVAL"] },
  { name: "Itsurvival", addr: "wss://itsurvival.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "JN | Network", addr: "wss://play.junarmc.xyz", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "PVE", "SKYBLOCK"] },
  { name: "KornCore", addr: "wss://core.kornineq.de/", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "PVP"] },
  { name: "Kryplex Network", addr: "wss://kryplex-network.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "MINIGAMES", "SURVIVAL", "RPG", "FACTIONS"] },
  { name: "Lamp Network", addr: "wss://mc.lampnetwork.xyz", verified: true, online: true, players: 65, votes: 0, tags: ["PVP", "MISCELLANEOUS", "SURVIVAL", "MINIGAMES"] },
  { name: "Lantern MC", addr: "wss://mc.lanternmc.cc", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "PVE"] },
  { name: "LightSMP", addr: "wss://lightsmp.eagler.host", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "MISCELLANEOUS", "MINIGAMES", "PVP"] },
  { name: "Lune Network", addr: "wss://lunenet.galacticnet.cfd", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "FACTIONS", "SURVIVAL"] },
  { name: "Mainbird Practice", addr: "wss://ec.mainbird.org", verified: true, online: false, players: 0, votes: 0, tags: ["PVP"] },
  { name: "Mazarca", addr: "wss://eagler.maza64.xyz", verified: true, online: true, players: 1, votes: 0, tags: ["SURVIVAL", "MINIGAMES", "PVP"] },
  { name: "mc.tantrum.org Anarchy", addr: "wss://mc.tantrum.org", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "PVE", "SURVIVAL"] },
  { name: "mineralia", addr: "wss://mineralia.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "Miserve demo", addr: "wss://miserve.zorner.men", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "MISCELLANEOUS", "FACTIONS"] },
  { name: "MysticMC", addr: "wss://play.mysticmc.ggff.net", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "MINIGAMES", "SKYBLOCK", "MISCELLANEOUS"] },
  { name: "Mytheria", addr: "wss://play.mytheriamc.net", verified: true, online: true, players: 15, votes: 0, tags: ["PVP", "SKYBLOCK", "RPG", "MISCELLANEOUS", "PVE"] },
  { name: "Mythical Network", addr: "wss://endis.my", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "Negratas SMP szn 2", addr: "wss://30090.ddnod.es", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "Neutine: Rebirth", addr: "wss://eg.neutine.net", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "MISCELLANEOUS", "RPG", "PVP", "PVE", "FACTIONS"] },
  { name: "Nexon MC", addr: "wss://nexon.nullsworld.net", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "MISCELLANEOUS", "MINIGAMES"] },
  { name: "NullCraft FACTIONS", addr: "wss://eag.xapktech.xyz/", verified: true, online: false, players: 0, votes: 0, tags: ["FACTIONS", "SURVIVAL", "PVP", "MISCELLANEOUS"] },
  { name: "Options", addr: "wss://options.theludos.com/", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "PVE", "PVP", "FACTIONS", "MISCELLANEOUS"] },
  { name: "PixelVerseMC", addr: "wss://thijmens.nl:4444/", verified: true, online: false, players: 0, votes: 0, tags: ["MINIGAMES", "SURVIVAL", "MISCELLANEOUS", "PVP"] },
  { name: "PizzaSMP", addr: "wss://pizzasmp.qzz.io", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "MISCELLANEOUS"] },
  { name: "PlebMc", addr: "wss://eagler.plebmc.top", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "MINIGAMES", "SURVIVAL", "RPG", "MISCELLANEOUS", "PVE", "FACTIONS"] },
  { name: "Pnut22 And Colbster937 smp", addr: "wss://pnutserver.colbster937.dev", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "Radiant Network", addr: "wss://eagler.radiantnet.club", verified: true, online: true, players: 46, votes: 0, tags: ["PVP", "MISCELLANEOUS", "SURVIVAL"] },
  { name: "RagePvP Network", addr: "wss://ragepvp.us", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "MINIGAMES", "SURVIVAL"] },
  { name: "ROBOANARCHY", addr: "wss://roboanarchy.eagler.host", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "FACTIONS", "MISCELLANEOUS", "SURVIVAL"] },
  { name: "Ruby Network", addr: "wss://mc.ruby-network.net", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "SKYBLOCK", "MINIGAMES"] },
  { name: "SHRIMPCRAFT", addr: "wss://eagler.wbfrrt.xyz", verified: true, online: true, players: 0, votes: 0, tags: ["MINIGAMES", "SURVIVAL"] },
  { name: "Simple Survival SMP", addr: "wss://sssmp.shares.zrok.io", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "FACTIONS"] },
  { name: "SimpleHardcore", addr: "wss://simplehardcore.eagler.host", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "Skyline Network", addr: "wss://play.skylinenet.lol", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "SURVIVAL"] },
  { name: "SteakMC", addr: "wss://steak.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "MINIGAMES", "PVP"] },
  { name: "Stellite Games Network", addr: "wss://stellite.games/eagler", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "PVE", "MISCELLANEOUS", "SURVIVAL"] },
  { name: "Storm-mc", addr: "wss://storm-mc.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "Stuffs", addr: "wss://stuffs.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "MISCELLANEOUS", "FACTIONS"] },
  { name: "SuckMyCraft", addr: "wss://eagler.suckmycraft.online/", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "SKYBLOCK", "MISCELLANEOUS"] },
  { name: "survival22", addr: "wss://survival22.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "MINIGAMES", "MISCELLANEOUS"] },
  { name: "SwaftMC", addr: "wss://study-tools.swaft.org", verified: true, online: true, players: 4, votes: 0, tags: ["PVE", "PVP", "SURVIVAL", "MINIGAMES", "SKYBLOCK", "PRISON", "MISCELLANEOUS"] },
  { name: "Switch SMP - Formely Val+", addr: "wss://32081.ddnod.es", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "MISCELLANEOUS"] },
  { name: "TeamHolyTOP", addr: "wss://eagle.teamholy.top", verified: true, online: false, players: 0, votes: 0, tags: ["MINIGAMES", "PVP", "SURVIVAL", "MISCELLANEOUS"] },
  { name: "Thanatos-Network", addr: "wss://web.thanatos-network.xyz", verified: true, online: true, players: 10, votes: 0, tags: ["SURVIVAL", "MINIGAMES"] },
  { name: "The Cottage (Hoplite Coming Soon)", addr: "wss://eagler.the-cottage.club", verified: true, online: true, players: 29, votes: 0, tags: ["PVP", "SURVIVAL", "CREATIVE", "PRISON", "MISCELLANEOUS", "RPG", "FACTIONS"] },
  { name: "The EagMP", addr: "wss://mc.theludos.com/", verified: true, online: true, players: 2, votes: 0, tags: ["SURVIVAL"] },
  { name: "TheBreadSMP", addr: "wss://thebreadsmp.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "PVP"] },
  { name: "Thunder Network", addr: "wss://play.thundernetwork.store/", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "MISCELLANEOUS", "MINIGAMES"] },
  { name: "TitanNetwork", addr: "wss://eagler.titannetwork.top/", verified: true, online: false, players: 0, votes: 0, tags: ["MISCELLANEOUS", "SURVIVAL"] },
  { name: "toxide", addr: "wss://toxide.eagler.host", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "PVP"] },
  { name: "TS_Gamer Craft", addr: "wss://tsgamercraft.eagler.host", verified: true, online: false, players: 0, votes: 0, tags: ["SKYBLOCK", "MINIGAMES", "SURVIVAL"] },
  { name: "tzenfore\u0027s Minecraft Server", addr: "wss://althacker.xyz:4443", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "UltraCraft", addr: "wss://play.ultrawyatt.com/", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "PVP", "PVE", "FACTIONS"] },
  { name: "Velkor Network | 1.8+ | ⛏️ OP Prison ⛏️ | Java \u0026 Eagler |", addr: "wss://velkor.club", verified: true, online: true, players: 0, votes: 0, tags: ["PRISON", "PVP", "PVE", "MISCELLANEOUS"] },
  { name: "Vexor", addr: "wss://vexor.cc", verified: true, online: true, players: 0, votes: 0, tags: ["PVP", "FACTIONS"] },
  { name: "VillaSmp", addr: "wss://villasmp.eagler.host/", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "Vortexium Network", addr: "wss://30086.ddnod.es", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "FACTIONS"] },
  { name: "Waffle-Network", addr: "wss://play.hostinghaven.us:45342", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "PVP", "MINIGAMES", "MISCELLANEOUS", "CREATIVE", "FACTIONS"] },
  { name: "WaterNetwork", addr: "wss://mc.waternett.online", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "MISCELLANEOUS"] },
  { name: "WegCraft", addr: "wss://craft.slaysisters.website", verified: true, online: false, players: 0, votes: 0, tags: ["PVP", "SURVIVAL", "MISCELLANEOUS"] },
  { name: "WysternCraft", addr: "wss://play.wysterncraft.xyz", verified: true, online: true, players: 0, votes: 0, tags: ["RPG", "SURVIVAL", "PVP", "FACTIONS", "MISCELLANEOUS", "PVE"] },
  { name: "Yeag MC", addr: "wss://server.dhyrk.com", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL"] },
  { name: "ZelimSMP", addr: "wss://smp.zelimmc.com", verified: true, online: false, players: 0, votes: 0, tags: ["SURVIVAL", "MINIGAMES", "PVP"] },
  { name: "Zombarchy", addr: "wss://zombarchy.eagler.host", verified: true, online: true, players: 0, votes: 0, tags: ["SURVIVAL", "PVE", "PVP", "FACTIONS", "MISCELLANEOUS"] },
];
